import {PrismaClient} from '@prisma/client';
import * as cheerio from 'cheerio';
const prisma=new PrismaClient();
const VISUAL='https://wikimon.net/Visual_List_of_Digimon';
const DUBS='https://wikimon.net/List_of_English_Dub_Names';
const norm=(s:string)=>s.normalize('NFKD').toLowerCase().replace(/x-antibody/g,'x').replace(/burst mode/g,'bm').replace(/crimson mode/g,'cm').replace(/fighter mode/g,'fm').replace(/dragon mode/g,'dm').replace(/paladin mode/g,'pm').replace(/rage mode/g,'rm').replace(/sleep mode/g,'sm').replace(/[^a-z0-9]+/g,'');
const clean=(s:string)=>s.replace(/\[[^\]]*\]/g,'').replace(/\s+/g,' ').trim();
const manual:Record<string,string>={
  'kapurimon':'Caprimon','tsunomon':'Tunomon','motimon':'Mochimon','snowgoblimon':'Snow Goburimon','chuumon':'Tyumon','dracmon':'Dracumon','mudfrigimon':'Chuchidarumon','shellnumemon':'Karatuki Numemon','sukamon':'Scumon','platinumsukamon':'Platinum Scumon','minotarumon':'Minotaurmon','lanamon':'Ranamon','calmaramon':'Calamaramon','kendogarurumon':'Garummon','rapidmon':'Rapidmon (Perfect)','meteormon':'Insekimon','deramon':'Delumon','hippogryphonmon':'Hippo Griffomon','shaujinmon':'Shawujinmon','phantomon':'Fantomon','lucemon-cm':'Lucemon: Falldown Mode','chronomon-hm':'Chronomon: Holy Mode','cherubimon-black':'Cherubimon (Vice)','cherubimon-good':'Cherubimon (Virtue)','ultimatebrachiomon':'Ultimate Brachimon','groundlocomon':'Grand Locomon','medievalgallantmon':'Medieval Dukemon','grandracmon':'Grand Dracumon','chronomon-dm':'Chronomon: Destroy Mode','bacchusmon-dm':'Bacchusmon: Drunk Mode','puppetmon':'Pinochimon','junomon-hm':'Junomon: Hysteric Mode','rusttyrannomon':'Rust Tyranomon','magnagarurumon-detached':'Magna Garurumon: Separation Mode','craniamon-plus-enbarrmon':'Craniummon + Enbarrmon','susanomon':'Susanoomon','jupitermon-wm':'Jupitermon: Wrath Mode','lucemon-sm':'Lucemon: Satan Mode','agumon-bond-of-bravery':'Agumon -Yuki no Kizuna-','gabumon-bond-of-friendship':'Gabumon -Yujo no Kizuna-','ulforceveedramon-x-antibody':'Ulforce V-dramon (X-Antibody)','magnamon-x-antibody':'Magnamon (X-Antibody)','jesmon-x-antibody':'Jesmon (X-Antibody)','gallantmon-x-antibody':'Dukemon (X-Antibody)','omnimon-x-antibody':'Omegamon (X-Antibody)',
  'aeroveedramon':'Aero V-dramon','agunimon':'Agnimon','armadillomon':'Armadimon','armageddemon':'Armagemon','arukenimon':'Archnemon','baohuckmon':'Bao Huckmon','beelstarmon':'Beel Starmon','beelzemon':'Beelzebumon','beelzemon-bm':'Beelzebumon: Blast Mode','birdramon':'Birdramon','biyomon':'Piyomon','blackgatomon':'Black Tailmon','blackwargreymon':'Black War Greymon','blimpmon':'Blimpmon','blitzgreymon':'Blitz Greymon','brachiomon':'Brachimon','burninggreymon':'Vritramon','calmaramon':'Calmaramon','centarumon':'Centalmon','cerberusmon':'Cerberumon','cerberusmon-wm':'Cerberumon: Werewolf Mode','chaosgallantmon':'Chaos Dukemon','cherrymon':'Jyureimon','chirinmon':'Tyilinmon','craniamon':'Craniummon','cresgarurumon':'Cres Garurumon','crowmon':'Yatagaramon','crabmon':'Ganimon','creepymon':'Demon','cyclonemon':'Cyclomon','datamon':'Nanomon','demidevimon':'Pico Devimon','deputymon':'Revolmon','diaboromon':'Diablomon','dinohyumon':'Dinohumon','divermon':'Hangyomon','dorumon':'DORUmon','dorugamon':'DORUgamon','dorugreymon':'DORUguremon','dorugoramon':'DORUgoramon','eaglemon':'Crossmon','ebemon':'EBEmon','exveemon':'XV-mon','flamedramon':'Fladramon','gallantmon':'Dukemon','gallantmon-cm':'Dukemon: Crimson Mode','gatomon':'Tailmon','goblimon':'Goburimon','goldramon':'Goddramon','gotsumon':'Gottsumon','grapleomon':'Grappu Leomon','greatgrizzlymon':'Great Gryzmon','grizzlymon':'Gryzmon','growlmon':'Growmon','huckmon':'Hackmon','kimeramon':'Chimairamon','kentaurosmon':'Sleipmon','kendogarurumon':'Garmmon','kudamon':'Kudamon','kurisarimon':'Chrysalimon','leopardmon':'Duftmon','leopardmon-lm':'Duftmon: Leopard Mode','lotosmon':'Lotusmon','lordknightmon':'Lord Knightmon','magnadramon':'Holydramon','magnaangemon':'Holy Angemon','machinedramon':'Mugendramon','malomyotismon':'Belial Vamdemon','megagargomon':'Saint Galgomon','megakabuterimon':'Atlur Kabuterimon (Red)','metalgreymon-blue':'Metal Greymon (Virus)','metalgarurumon-black':'Metal Garurumon (Black)','myotismon':'Vamdemon','omnimon':'Omegamon','omnimon-zwart':'Omegamon Zwart','omnimon-zwart-defeat':'Omegamon Zwart Defeat','omnimon-alter-s':'Omegamon Alter-S','omnimon-alter-b':'Omegamon Alter-B','omnimon-mm':'Omegamon: Merciful Mode','ophanimon':'Ofanimon','paildramon':'Paildramon','parrotmon':'Parrotmon','phoenixmon':'Hououmon','piedmon':'Piemon','puppetmon':'Pinocchimon','ravemon':'Ravmon','ravemon-bm':'Ravmon: Burst Mode','shinegreymon':'Shine Greymon','shinegreymon-bm':'Shine Greymon: Burst Mode','silphymon':'Silphymon','sorcermon':'Sorcerimon','syakomon':'Shakomon','tapirmon':'Bakumon','veedramon':'V-dramon','vulcanusmon':'Vulcanusmon','waruseadramon':'Waru Seadramon','wargrowlmon':'Megalo Growmon'};
async function html(url:string){const r=await fetch(url,{headers:{'user-agent':'DTS-Companion-Wikimon-Image-Importer/1.0'}});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.text()}
function imageMap(source:string){const $=cheerio.load(source),map=new Map<string,{name:string,url:string}>();$('table').each((_,table)=>{const img=$(table).find('img').first();const link=$(table).find('tr').last().find('a').first();const name=clean(link.attr('title')||link.text()||img.attr('alt')||'');if(!name||!img.length)return;const set=img.attr('srcset')?.split(',').map(x=>x.trim().split(/\s+/)[0]).filter(Boolean);const path=set?.at(-1)||img.attr('src');if(path)map.set(norm(name),{name,url:new URL(path,'https://wikimon.net').href})});return map}
function dubMap(source:string){const $=cheerio.load(source),map=new Map<string,string>();$('table tr').each((_,row)=>{const cells=$(row).find('td');if(cells.length<2)return;const english=clean(cells.eq(0).find('a').first().text()||cells.eq(0).text());const japanese=clean(cells.eq(cells.length-1).text()).split(/\s{2,}|\n/)[0];if(english&&japanese&&!/see /i.test(cells.eq(0).text()))map.set(norm(english),japanese)});return map}
async function main(){const[visualHtml,dubHtml,mons]=await Promise.all([html(VISUAL),html(DUBS),prisma.digimon.findMany({orderBy:{fieldGuideNo:'asc'}})]);const images=imageMap(visualHtml),dubs=dubMap(dubHtml);let matched=0;const misses:string[]=[];for(const mon of mons){const manualName=manual[mon.slug];const dubName=dubs.get(norm(mon.name));const candidates=[manualName,dubName,mon.name].filter(Boolean) as string[];const hit=candidates.map(name=>images.get(norm(name))).find(Boolean);if(!hit){misses.push(mon.name);continue}await prisma.digimon.update({where:{id:mon.id},data:{imageUrl:hit!.url}});matched++}console.log(JSON.stringify({total:mons.length,matched,unmatched:misses.length,misses},null,2))}
main().finally(()=>prisma.$disconnect());
