'use client';
import {useEffect,useMemo,useState} from 'react';
import {getSettings,setSettings} from '../lib/userState';
import {ps5Profile} from '../lib/cheatData';
import {bundledSwitchCheats,bundledSwitchMeta,switchMasterCode} from '../lib/switchCheats.generated';
import {bundledSwitchDemoCheats,bundledSwitchDemoMeta,switchDemoMasterCode} from '../lib/switchDemoCheats.generated';

type SwitchCode={id:string;name:string;description?:string;code:string;category?:string;source?:string;credits?:string;buildId?:string};
const hexLine=/^[0-9a-f]{8}(?:\s+[0-9a-f]{8}){0,3}$/i;

function parseAtmosphere(input:string){
  const items:SwitchCode[]=[];let current:SwitchCode|null=null;
  for(const raw of input.replace(/\r/g,'').split('\n')){const line=raw.trim();const heading=line.match(/^\[([^\]]+)\]$/);if(heading){current={id:`switch-${Date.now()}-${items.length}`,name:heading[1].trim(),code:''};items.push(current)}else if(current&&hexLine.test(line))current.code+=(current.code?'\n':'')+line.toUpperCase()}
  return items.filter(x=>x.name&&x.code);
}
function download(name:string,data:BlobPart,type='text/plain;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function bytes(...values:number[]){return new Uint8Array(values)}
function u16(n:number){return bytes(n&255,(n>>>8)&255)}function u32(n:number){return bytes(n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255)}
function join(parts:Uint8Array[]){const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let at=0;for(const p of parts){out.set(p,at);at+=p.length}return out}
function crc32(data:Uint8Array){let c=0xffffffff;for(const b of data){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
function makeZip(files:{name:string;content:string}[]){const encoder=new TextEncoder(),locals:Uint8Array[]=[],centrals:Uint8Array[]=[];let offset=0;for(const file of files){const name=encoder.encode(file.name),data=encoder.encode(file.content),crc=crc32(data),local=join([u32(0x04034b50),u16(20),u16(0x800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);centrals.push(join([u32(0x02014b50),u16(20),u16(20),u16(0x800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length}const body=join(locals),central=join(centrals),end=join([u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(central.length),u32(body.length),u16(0)]);return join([body,central,end])}

export default function CheatClient(){
  const[platform,setPlatform]=useState<'switch'|'ps5'>('switch'),[switchBuild,setSwitchBuild]=useState<'retail'|'demo'>('retail'),[codes,setCodes]=useState<SwitchCode[]>([]),[selectedSwitch,setSelectedSwitch]=useState<string[]>([]),[selectedPs5,setSelectedPs5]=useState<string[]>([]),[paste,setPaste]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState('All');
  useEffect(()=>{const saved=getSettings().cheatWorkspace,clean=(saved?.switchCodes??[]).filter(x=>!(x.name==='Test Entry'&&x.code.includes('01234567'))),validIds=new Set([...bundledSwitchCheats.map(x=>x.id),...bundledSwitchDemoCheats.map(x=>x.id),...clean.map(x=>x.id)]);setPlatform(saved?.platform??'switch');setSwitchBuild(saved?.switchBuild??'retail');setCodes(clean);setSelectedSwitch((saved?.selectedSwitch??[]).filter(x=>validIds.has(x)));setSelectedPs5(saved?.selectedPs5??[])},[]);
  useEffect(()=>{if(!codes.length&&!selectedSwitch.length&&!selectedPs5.length)return;const settings=getSettings();setSettings({...settings,cheatWorkspace:{platform,switchBuild,switchCodes:codes,selectedSwitch,selectedPs5}})},[platform,switchBuild,codes,selectedSwitch,selectedPs5]);
  const switchCatalog=switchBuild==='demo'?{meta:bundledSwitchDemoMeta,codes:bundledSwitchDemoCheats,masterCode:switchDemoMasterCode}:{meta:bundledSwitchMeta,codes:bundledSwitchCheats,masterCode:switchMasterCode};
  const allSwitchCodes=useMemo(()=>[...switchCatalog.codes.map(x=>({...x,buildId:switchCatalog.meta.buildId})),...codes.filter(x=>(x.buildId??bundledSwitchMeta.buildId)===switchCatalog.meta.buildId)],[codes,switchCatalog.codes,switchCatalog.meta.buildId]);
  const chosenSwitch=useMemo(()=>allSwitchCodes.filter(x=>selectedSwitch.includes(x.id)),[allSwitchCodes,selectedSwitch]);
  const categories=useMemo(()=>['All',...new Set(switchCatalog.codes.map(x=>x.category))],[switchCatalog.codes]);
  const visibleSwitch=useMemo(()=>allSwitchCodes.filter(x=>(category==='All'||x.category===category)&&(!search||`${x.name} ${x.description??''} ${x.category??''}`.toLowerCase().includes(search.toLowerCase()))),[allSwitchCodes,category,search]);
  const chosenPs5=useMemo(()=>ps5Profile.mods.filter(x=>selectedPs5.includes(x.id)),[selectedPs5]);
  const switchText=`[MASTER RESTORE/OFF ENABLE]\n${switchCatalog.masterCode}\n\n`+chosenSwitch.map(x=>`[${x.name}]\n${x.code}`).join('\n\n')+'\n';
  const ps5Json=JSON.stringify({...ps5Profile,source:undefined,mods:chosenPs5.map(({id,description,...mod})=>mod)},null,2)+'\n';
  function importCodes(){const parsed=parseAtmosphere(paste).map(x=>({...x,buildId:switchCatalog.meta.buildId}));if(!parsed.length){setMessage('No valid Atmosphere entries found. Use [Cheat name] followed by hexadecimal instruction lines.');return}setCodes(old=>[...old,...parsed]);setSelectedSwitch(old=>[...old,...parsed.map(x=>x.id)]);setPaste('');setMessage(`${parsed.length} cheat${parsed.length===1?'':'s'} added to ${switchCatalog.meta.version} and selected.`)}
  function toggle(list:string[],set:(v:string[])=>void,id:string){set(list.includes(id)?list.filter(x=>x!==id):[...list,id])}
  function exportHatsZip(){if(!chosenSwitch.length)return setMessage('Select at least one valid Switch cheat first.');download(`DTS-HATS-${switchBuild==='demo'?'Demo-1.0.0':'1.2.1'}.zip`,makeZip([{name:`atmosphere/contents/${switchCatalog.meta.titleId}/cheats/${switchCatalog.meta.buildId}.txt`,content:switchText}]),'application/zip')}
  function exportPs5Zip(){if(!chosenPs5.length)return setMessage('Select at least one PS5 cheat first.');download('DTS-etaHEN-01.000.011.zip',makeZip([{name:`data/etaHEN/cheats/json/${ps5Profile.id}_${ps5Profile.version}.json`,content:ps5Json}]),'application/zip')}
  function exportCht(){if(!chosenSwitch.length)return setMessage('Select at least one Switch cheat first.');const text=[`cheats = "${chosenSwitch.length}"`,...chosenSwitch.flatMap((x,i)=>[`cheat${i}_desc = "${x.name.replaceAll('"','\\"')}"`,`cheat${i}_code = "${x.code.replaceAll('\n','+')}"`,`cheat${i}_enable = "false"`])].join('\n\n')+'\n';download('Digimon Story Time Stranger.cht',text)}
  return <>
    <section className="card cheat-platforms"><button className={platform==='switch'?'active':''} onClick={()=>setPlatform('switch')}><span className="platform-icon">NX</span><span><b>Nintendo Switch</b><small>HATS · Atmosphère</small></span></button><button className={platform==='ps5'?'active':''} onClick={()=>setPlatform('ps5')}><span className="platform-icon">5</span><span><b>PlayStation 5</b><small>etaHEN JSON</small></span></button></section>
    {platform==='switch'&&<details className="card hats-guide" open>
      <summary><span><b>How to use cheats with HATS</b><small>From this page to the EdiZon overlay</small></span><span className="guide-toggle">Installation guide</span></summary>
      <div className="hats-guide-body">
        <ol className="hats-steps">
          <li><span>1</span><div><b>Choose the matching game build</b><p>Select Full Game or Demo above the cheat catalog. Cheats only load when the Build ID exactly matches your installed game.</p></div></li>
          <li><span>2</span><div><b>Select and export</b><p>Choose a small number of cheats to test, then press <strong>Export HATS ZIP</strong>. The restore/master entry is included automatically.</p></div></li>
          <li><span>3</span><div><b>Copy to the SD card</b><p>Back up your save with JKSV. Extract the ZIP into the root of the Switch SD card and merge folders when prompted—do not copy the ZIP itself.</p></div></li>
          <li><span>4</span><div><b>Enable cheats in-game</b><p>Boot HATS/Atmosphère, load your save, open the overlay with <kbd>L</kbd> + <kbd>↓</kbd> + <kbd>R3</kbd>, then choose <strong>EdiZon → Cheats</strong> and press <kbd>A</kbd> on a cheat.</p></div></li>
        </ol>
        <div className="hats-guide-info">
          <div><small>Selected Build ID</small><code>{switchCatalog.meta.buildId}</code></div>
          <div><small>SD card destination</small><code>/atmosphere/contents/{switchCatalog.meta.titleId}/cheats/{switchCatalog.meta.buildId}.txt</code></div>
          <p className="warning"><b>Start safely:</b> back up your save and enable only one or two cheats first. If an effect remains after turning it off, enable <strong>MASTER RESTORE/OFF ENABLE</strong> once, then disable it again.</p>
          <p className="muted small">If EdiZon shows no cheats, confirm the game update matches this Build ID and that the extracted file is in the destination shown above.</p>
        </div>
      </div>
    </details>}
    {platform==='switch'?<div className="cheat-layout">
      <section><div className="card build-card"><div><span className="verified">Verified build catalog</span><h2>Switch {switchCatalog.meta.version}</h2><p className="muted small">{switchCatalog.meta.count} selectable cheats · {switchCatalog.meta.sourceFiles} source export{switchCatalog.meta.sourceFiles===1?'':'s'}</p></div><div><label className="switch-build-picker">Game build<select value={switchBuild} onChange={e=>{setSwitchBuild(e.target.value as 'retail'|'demo');setCategory('All');setSearch('')}}><option value="retail">Full Game 1.2.1</option><option value="demo">Demo 1.0.0</option></select></label><dl><div><dt>Title ID</dt><dd>{switchCatalog.meta.titleId}</dd></div><div><dt>Build ID</dt><dd>{switchCatalog.meta.buildId}</dd></div></dl></div><p className="warning">Codes only work on the exact matching build. The required restore/master block is added automatically to every export.</p></div>
      <div className="section-title"><h2>Selectable cheats</h2><span className="muted small">{chosenSwitch.length} selected</span></div><div className="card cheat-catalog-tools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search titles, effects, or categories…"/><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>setSelectedSwitch([...new Set([...selectedSwitch,...visibleSwitch.map(x=>x.id)])])}>Select visible</button><button onClick={()=>{const currentIds=new Set(allSwitchCodes.map(x=>x.id));setSelectedSwitch(selectedSwitch.filter(x=>!currentIds.has(x)))}}>Clear</button></div><div className="cheat-list">{visibleSwitch.map(code=><label className="card cheat-option" key={code.id}><input type="checkbox" checked={selectedSwitch.includes(code.id)} onChange={()=>toggle(selectedSwitch,setSelectedSwitch,code.id)}/><span><b>{code.name}</b>{code.description&&<small className="cheat-description">{code.description}</small>}<small className="cheat-meta">{code.category??'Custom'} · {code.code.split('\n').length} instruction line{code.code.includes('\n')?'s':''}{code.source?` · ${code.source}`:''}</small></span>{!code.source&&<button onClick={e=>{e.preventDefault();setCodes(codes.filter(x=>x.id!==code.id));setSelectedSwitch(selectedSwitch.filter(x=>x!==code.id))}} aria-label={`Remove ${code.name}`}>×</button>}</label>)}</div>{!visibleSwitch.length&&<div className="empty">No cheats match this search.</div>}</section>
      <aside className="card cheat-export"><h2>Build HATS package</h2><p className="muted">The package is generated for <b>{switchCatalog.meta.version}</b>. Paste additional Atmosphère entries only when they match this Build ID.</p><textarea value={paste} onChange={e=>setPaste(e.target.value)} placeholder={'[Cheat name]\n04000000 AAAAAAAA BBBBBBBB'} rows={9}/><button onClick={importCodes}>Add entries</button><div className="install-path"><small>Install path inside ZIP</small><code>/atmosphere/contents/{switchCatalog.meta.titleId}/cheats/{switchCatalog.meta.buildId}.txt</code></div><button className="primary" onClick={exportHatsZip}>Export HATS ZIP</button><button onClick={()=>chosenSwitch.length?download(`${switchCatalog.meta.buildId}.txt`,switchText):setMessage('Select at least one Switch cheat first.')}>Export .txt</button><button onClick={exportCht}>Export generic .cht</button><small className="muted">The .txt/ZIP exports are HATS-compatible. The .cht export is a generic RetroArch-style archive and is not used by HATS.</small></aside>
    </div>:<div className="cheat-layout">
      <section><div className="card build-card"><div><span className="verified">Verified community profile</span><h2>PS5 {ps5Profile.version}</h2></div><dl><div><dt>Title ID</dt><dd>{ps5Profile.id}</dd></div><div><dt>Process</dt><dd>{ps5Profile.process}</dd></div></dl><p className="warning">This profile must match the exact PS5 Title ID and game version. Create a save backup before use.</p></div><div className="section-title"><h2>Select cheats</h2><span className="muted small">{chosenPs5.length} selected</span></div><div className="cheat-list">{ps5Profile.mods.map(mod=><label className="card cheat-option" key={mod.id}><input type="checkbox" checked={selectedPs5.includes(mod.id)} onChange={()=>toggle(selectedPs5,setSelectedPs5,mod.id)}/><span><b>{mod.name}</b><small>{mod.description}</small></span></label>)}</div></section>
      <aside className="card cheat-export"><h2>Build etaHEN package</h2><p className="muted">Exports only the selected entries in the established PS5 JSON format.</p><div className="install-path"><small>Install path inside ZIP</small><code>/data/etaHEN/cheats/json/{ps5Profile.id}_{ps5Profile.version}.json</code></div><button className="primary" onClick={exportPs5Zip}>Export etaHEN ZIP</button><button onClick={()=>chosenPs5.length?download(`${ps5Profile.id}_${ps5Profile.version}.json`,ps5Json,'application/json'):setMessage('Select at least one PS5 cheat first.')}>Export .json</button><a className="button" href={ps5Profile.source} target="_blank" rel="noreferrer">View original source ↗</a><small className="muted">Credits: {ps5Profile.credits.join(', ')}. Source values are preserved exactly.</small></aside>
    </div>}
    {message&&<div className="cheat-toast" role="status"><span>{message}</span><button onClick={()=>setMessage('')}>×</button></div>}
  </>
}
