'use client';
import {useEffect,useMemo,useState} from 'react';
import {missions,type Mission} from '../lib/missionData';
import {getSettings,setSettings} from '../lib/userState';

export default function GuideClient(){
  const[q,setQ]=useState(''),[kind,setKind]=useState('All'),[chapter,setChapter]=useState('All'),[done,setDone]=useState<Set<string>>(new Set()),[open,setOpen]=useState('');
  useEffect(()=>setDone(new Set(getSettings().missionProgress??[])),[]);
  function toggle(id:string){const next=new Set(done);next.has(id)?next.delete(id):next.add(id);setDone(next);setSettings({...getSettings(),missionProgress:[...next]})}
  const chapters=[...new Set(missions.filter(m=>kind==='All'||m.kind===kind).map(m=>m.chapter))];
  const items=useMemo(()=>missions.filter(m=>{const haystack=`${m.title} ${m.chapter} ${m.location} ${m.summary} ${m.steps.join(' ')} ${m.tips.join(' ')}`.toLowerCase();return(kind==='All'||m.kind===kind)&&(chapter==='All'||m.chapter===chapter)&&(!q||haystack.includes(q.toLowerCase()));}),[q,kind,chapter]);
  return <><section className="card guide-summary"><div><strong>{done.size} / {missions.length}</strong><span className="muted"> missions complete</span><div className="progress"><div style={{width:`${Math.round(done.size/missions.length*100)}%`}}/></div></div><p className="muted small">Progress is stored locally and syncs automatically when signed in.</p></section><section className="card guide-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search missions, locations, objectives or tips…"/><select value={kind} onChange={e=>{setKind(e.target.value);setChapter('All')}}><option>All</option><option>Main</option><option>Side</option><option>Post-game</option><option>DLC</option></select><select value={chapter} onChange={e=>setChapter(e.target.value)}><option>All</option>{chapters.map(c=><option key={c}>{c}</option>)}</select><span className="muted small">{items.length} results</span></section><div className="mission-list">{items.map((m:Mission)=><article className={`card mission-card ${done.has(m.id)?'completed':''}`} key={m.id}><label className="mission-check" title="Mark mission complete"><input type="checkbox" checked={done.has(m.id)} onChange={()=>toggle(m.id)}/><span/></label><button className="mission-main" onClick={()=>setOpen(open===m.id?'':m.id)} aria-expanded={open===m.id} aria-controls={`${m.id}-details`}><span className={`mission-kind ${m.kind.toLowerCase()}`}>{m.kind}</span><span><strong>{m.title}</strong><small>{m.chapter}</small></span><b aria-hidden>{open===m.id?'−':'+'}</b></button>{open===m.id&&<div className="mission-details" id={`${m.id}-details`}><div className="mission-meta"><span>📍 {m.location}</span><span>{m.steps.length} steps</span></div><p className="mission-summary">{m.summary}</p>{m.unlock&&<div className="mission-unlock"><b>Unlock requirement</b><span>{m.unlock}</span></div>}<h3>Walkthrough</h3><ol className="walkthrough-steps">{m.steps.map((step,index)=><li key={index}><span>{index+1}</span><p>{step}</p></li>)}</ol>{m.tips.length>0&&<div className="mission-tips"><h3>Preparation & notes</h3><ul>{m.tips.map((tip,index)=><li key={index}>{tip}</li>)}</ul></div>}<div className="source-note"><span>✓ Complete this route without leaving the companion.</span></div></div>}</article>)}</div><div className="card guide-disclosure"><b>In-app guide coverage</b><p className="muted">Every listed main, side, post-game and downloadable mission now opens inside the companion. The route text is an original practical summary of confirmed objectives; uncertain item quantities, rewards or enemy values are omitted instead of guessed.</p></div></>;
}
